modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="stevescarts" #mandatory
version="${file.jarVersion}" #mandatory
displayName="StevesCarts2" #mandatory
logoFile="examplemod.png" #optional
credits="" #optional
authors="CreeperHost" #optional
description='''

'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.stevescarts]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.stevescarts]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18, )"
    ordering="NONE"
    side="BOTH"
